---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-repo-deployment
  labels:
    app: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: doomedmonk13/test1:49
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: dockerhubcred

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
      app: myapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
