---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: $APP_NAME
spec:
  replicas: 2
  selector:
    matchLabels:
      app: $APP_NAME
  template:
    metadata:
      labels:
        app: $APP_NAME
    spec:
      containers:
      - name: $APP_NAME
        image: $DOCKER_REPO:$IMAGE_TAG
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      imagePullSecrets:
        - name: ecrcred


---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  selector:
      app: $APP_NAME
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
